# Generated by Django 2.1.2 on 2018-11-22 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quotetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmPassword', models.TextField(blank=True, max_length=100, null=True)),
                ('created_Date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('deviceToken', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('firstname', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.TextField(blank=True, max_length=100, null=True)),
                ('firebase_id', models.TextField(blank=True, max_length=500, null=True)),
                ('lastName', models.TextField(blank=True, max_length=100, null=True)),
                ('password', models.TextField(blank=True, max_length=100, null=True)),
                ('profilePic', models.TextField(blank=True, null=True, verbose_name=models.TextField(validators=[django.core.validators.URLValidator()]))),
                ('username', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
