# Generated by Django 2.1.2 on 2018-11-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quotetable',
            new_name='angeltable',
        ),
    ]
