# Generated by Django 2.1.2 on 2018-12-15 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0003_fcm_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation', models.TextField(blank=True, max_length=500, null=True)),
                ('firebase_id', models.TextField(blank=True, max_length=500, null=True)),
                ('interaction', models.TextField(blank=True, max_length=100, null=True)),
                ('isConsulted', models.TextField(blank=True, max_length=100, null=True)),
                ('issue', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='theripsttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_Date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('deviceToken', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('firstname', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.TextField(blank=True, max_length=100, null=True)),
                ('firebase_id', models.TextField(blank=True, max_length=500, null=True)),
                ('lastName', models.TextField(blank=True, max_length=100, null=True)),
                ('profession', models.TextField(blank=True, max_length=10000, null=True)),
                ('profilePic', models.TextField(blank=True, null=True, verbose_name=models.TextField(validators=[django.core.validators.URLValidator()]))),
                ('userId', models.TextField(blank=True, max_length=1000, null=True)),
                ('username', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
