# Generated by Django 2.1.2 on 2019-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0004_question_set_theripsttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.TextField(blank=True, max_length=500, null=True)),
                ('quotes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='question_set',
            old_name='interaction',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='question_set',
            old_name='expectation',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='question_set',
            name='isConsulted',
        ),
        migrations.RemoveField(
            model_name='question_set',
            name='issue',
        ),
    ]
