# Generated by Django 2.1.2 on 2019-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelapp', '0005_auto_20190103_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='angeltable',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
